include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unnecessary_const: info

formatter:
  trailing_commas: preserve   

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    
